"""Create messages table

Revision ID: 394103f78ddc
Revises: 
Create Date: 2025-06-20 00:49:20.956970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394103f78ddc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
