"""Create messages table

Revision ID: 79a6ebb75fe5
Revises: 394103f78ddc
Create Date: 2025-06-20 01:01:46.601254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a6ebb75fe5'
down_revision = '394103f78ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
